/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as AlunosIndexRouteImport } from './routes/alunos/index'
import { Route as AlunosIdRouteImport } from './routes/alunos/$id'
import { Route as CapacitacaoIndexRouteImport } from './routes/capacitacao/index'
import { Route as CapacitacaoFlashcardsRouteImport } from './routes/capacitacao/flashcards'
import { Route as PlanejamentoIndexRouteImport } from './routes/planejamento/index'
import { Route as PlanejamentoResultadoRouteImport } from './routes/planejamento/resultado'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosIndexRoute = AlunosIndexRouteImport.update({
  id: '/alunos/',
  path: '/alunos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosIdRoute = AlunosIdRouteImport.update({
  id: '/alunos/$id',
  path: '/alunos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacitacaoIndexRoute = CapacitacaoIndexRouteImport.update({
  id: '/capacitacao/',
  path: '/capacitacao/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacitacaoFlashcardsRoute = CapacitacaoFlashcardsRouteImport.update({
  id: '/capacitacao/flashcards',
  path: '/capacitacao/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoIndexRoute = PlanejamentoIndexRouteImport.update({
  id: '/planejamento/',
  path: '/planejamento/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoResultadoRoute = PlanejamentoResultadoRouteImport.update({
  id: '/planejamento/resultado',
  path: '/planejamento/resultado',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/relatorios': typeof RelatoriosRoute
  '/alunos/$id': typeof AlunosIdRoute
  '/capacitacao/flashcards': typeof CapacitacaoFlashcardsRoute
  '/planejamento/resultado': typeof PlanejamentoResultadoRoute
  '/alunos/': typeof AlunosIndexRoute
  '/capacitacao/': typeof CapacitacaoIndexRoute
  '/planejamento/': typeof PlanejamentoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/relatorios': typeof RelatoriosRoute
  '/alunos/$id': typeof AlunosIdRoute
  '/capacitacao/flashcards': typeof CapacitacaoFlashcardsRoute
  '/planejamento/resultado': typeof PlanejamentoResultadoRoute
  '/alunos': typeof AlunosIndexRoute
  '/capacitacao': typeof CapacitacaoIndexRoute
  '/planejamento': typeof PlanejamentoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/relatorios': typeof RelatoriosRoute
  '/alunos/$id': typeof AlunosIdRoute
  '/capacitacao/flashcards': typeof CapacitacaoFlashcardsRoute
  '/planejamento/resultado': typeof PlanejamentoResultadoRoute
  '/alunos/': typeof AlunosIndexRoute
  '/capacitacao/': typeof CapacitacaoIndexRoute
  '/planejamento/': typeof PlanejamentoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/relatorios'
    | '/alunos/$id'
    | '/capacitacao/flashcards'
    | '/planejamento/resultado'
    | '/alunos/'
    | '/capacitacao/'
    | '/planejamento/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/relatorios'
    | '/alunos/$id'
    | '/capacitacao/flashcards'
    | '/planejamento/resultado'
    | '/alunos'
    | '/capacitacao'
    | '/planejamento'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/relatorios'
    | '/alunos/$id'
    | '/capacitacao/flashcards'
    | '/planejamento/resultado'
    | '/alunos/'
    | '/capacitacao/'
    | '/planejamento/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  AlunosIdRoute: typeof AlunosIdRoute
  CapacitacaoFlashcardsRoute: typeof CapacitacaoFlashcardsRoute
  PlanejamentoResultadoRoute: typeof PlanejamentoResultadoRoute
  AlunosIndexRoute: typeof AlunosIndexRoute
  CapacitacaoIndexRoute: typeof CapacitacaoIndexRoute
  PlanejamentoIndexRoute: typeof PlanejamentoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos/': {
      id: '/alunos/'
      path: '/alunos'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AlunosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos/$id': {
      id: '/alunos/$id'
      path: '/alunos/$id'
      fullPath: '/alunos/$id'
      preLoaderRoute: typeof AlunosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacitacao/': {
      id: '/capacitacao/'
      path: '/capacitacao'
      fullPath: '/capacitacao/'
      preLoaderRoute: typeof CapacitacaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacitacao/flashcards': {
      id: '/capacitacao/flashcards'
      path: '/capacitacao/flashcards'
      fullPath: '/capacitacao/flashcards'
      preLoaderRoute: typeof CapacitacaoFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento/': {
      id: '/planejamento/'
      path: '/planejamento'
      fullPath: '/planejamento/'
      preLoaderRoute: typeof PlanejamentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento/resultado': {
      id: '/planejamento/resultado'
      path: '/planejamento/resultado'
      fullPath: '/planejamento/resultado'
      preLoaderRoute: typeof PlanejamentoResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  RelatoriosRoute: RelatoriosRoute,
  AlunosIdRoute: AlunosIdRoute,
  CapacitacaoFlashcardsRoute: CapacitacaoFlashcardsRoute,
  PlanejamentoResultadoRoute: PlanejamentoResultadoRoute,
  AlunosIndexRoute: AlunosIndexRoute,
  CapacitacaoIndexRoute: CapacitacaoIndexRoute,
  PlanejamentoIndexRoute: PlanejamentoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
